-- Table: realtime_subway_positions

CREATE TABLE public.realtime_subway_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_id VARCHAR(50),                -- subwayId: 1001:1호선, etc.
    line_name VARCHAR(50),              -- subwayNm: 1호선
    station_id VARCHAR(50),             -- statnId
    station_name VARCHAR(50),           -- statnNm
    train_number VARCHAR(50),           -- trainNo
    last_received_date VARCHAR(8),      -- lastRecptnDt: YYYYMMDD
    last_received_time TIMESTAMP,       -- recptnDt: YYYY-MM-DD HH:mm:ss
    direction_type INTEGER,             -- updnLine: 0:Up, 1:Down
    destination_station_id VARCHAR(50), -- statnTid
    destination_station_name VARCHAR(50),-- statnTnm
    train_status_code INTEGER,          -- trainSttus: 0:Enter, 1:Arrive, 2:Depart
    is_express BOOLEAN,                 -- directAt: 1:Express, 0:No
    is_last_train BOOLEAN,              -- lstcarAt: 1:Yes, 0:No
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('Asia/Seoul', now())
);

COMMENT ON COLUMN public.realtime_subway_positions.line_id IS '지하철호선ID (1001:1호선 등)';
COMMENT ON COLUMN public.realtime_subway_positions.line_name IS '지하철호선명';
COMMENT ON COLUMN public.realtime_subway_positions.station_id IS '지하철역ID';
COMMENT ON COLUMN public.realtime_subway_positions.station_name IS '지하철역명';
COMMENT ON COLUMN public.realtime_subway_positions.train_number IS '열차번호';
COMMENT ON COLUMN public.realtime_subway_positions.last_received_date IS '최종수신날짜 (YYYYMMDD)';
COMMENT ON COLUMN public.realtime_subway_positions.last_received_time IS '최종수신시간';
COMMENT ON COLUMN public.realtime_subway_positions.direction_type IS '상하행선구분 (0:상행/내선, 1:하행/외선)';
COMMENT ON COLUMN public.realtime_subway_positions.destination_station_id IS '종착지하철역ID';
COMMENT ON COLUMN public.realtime_subway_positions.destination_station_name IS '종착지하철역명';
COMMENT ON COLUMN public.realtime_subway_positions.train_status_code IS '열차상태구분 (0:진입, 1:도착, 2:출발, 3:전역출발)';
COMMENT ON COLUMN public.realtime_subway_positions.is_express IS '급행여부 (1:급행, 0:일반, 7:특급)';
COMMENT ON COLUMN public.realtime_subway_positions.is_last_train IS '막차여부 (1:막차, 0:아님)';
COMMENT ON COLUMN public.realtime_subway_positions.created_at IS '데이터 적재 시각 (KST)';
