-- 테이블 생성: realtime_subway_positions
CREATE TABLE IF NOT EXISTS realtime_subway_positions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_id VARCHAR(50) NOT NULL,          -- subwayId: 지하철 호선 ID
    line_name VARCHAR(100) NOT NULL,       -- subwayNm: 지하철 호선명
    station_id VARCHAR(50) NOT NULL,       -- statnId: 지하철 역 ID
    station_name VARCHAR(100) NOT NULL,    -- statnNm: 지하철 역명
    train_number VARCHAR(50) NOT NULL,     -- trainNo: 열차 번호
    last_rec_date VARCHAR(20),             -- lastRecptnDt: 최종 수신 날짜
    last_rec_time VARCHAR(20),             -- recptnDt: 최종 수신 시간
    direction_type VARCHAR(10),             -- updnLine: 0:상행/내선, 1:하행/외선
    dest_station_id VARCHAR(50),           -- statnTid: 종착역 ID
    dest_station_name VARCHAR(100),        -- statnTnm: 종착역명
    train_status VARCHAR(10),              -- trainSttus: 0:진입, 1:도착, 2:출발, ...
    is_express VARCHAR(10),                -- directAt: 1:급행, 0:아님, 7:특급
    is_last_train BOOLEAN,                 -- lstcarAt: 막차 여부
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() -- 데이터 적재 시간
);

-- 인덱스 설정 (조회 성능 최적화)
CREATE INDEX IF NOT EXISTS idx_realtime_positions_line_id ON realtime_subway_positions(line_id);
CREATE INDEX IF NOT EXISTS idx_realtime_positions_train_number ON realtime_subway_positions(train_number);
CREATE INDEX IF NOT EXISTS idx_realtime_positions_created_at ON realtime_subway_positions(created_at);

COMMENT ON TABLE realtime_subway_positions IS '서울시 실시간 지하철 위치 정보';
COMMENT ON COLUMN realtime_subway_positions.line_id IS '지하철 호선 ID';
COMMENT ON COLUMN realtime_subway_positions.line_name IS '지하철 호선명';
COMMENT ON COLUMN realtime_subway_positions.station_id IS '지하철 역 ID';
COMMENT ON COLUMN realtime_subway_positions.station_name IS '지하철 역명';
COMMENT ON COLUMN realtime_subway_positions.train_number IS '열차 번호';
COMMENT ON COLUMN realtime_subway_positions.last_rec_date IS '최종 수신 날짜';
COMMENT ON COLUMN realtime_subway_positions.last_rec_time IS '최종 수신 시간';
COMMENT ON COLUMN realtime_subway_positions.direction_type IS '0:상행/내선, 1:하행/외선';
COMMENT ON COLUMN realtime_subway_positions.dest_station_id IS '종착역 ID';
COMMENT ON COLUMN realtime_subway_positions.dest_station_name IS '종착역명';
COMMENT ON COLUMN realtime_subway_positions.train_status IS '0:진입, 1:도착, 2:출발, ...';
COMMENT ON COLUMN realtime_subway_positions.is_express IS '1:급행, 0:아님, 7:특급';
COMMENT ON COLUMN realtime_subway_positions.is_last_train IS '막차 여부';
COMMENT ON COLUMN realtime_subway_positions.created_at IS '데이터 적재 시간';
